services:
  backend:
    build:
      context: ./backend
    image: mern_app-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app  # Use Docker-managed volume
    networks:
      - mern-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    image: mern_app-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/app  # Use Docker-managed volume
    networks:
      - mern-network
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27021:27017"
    volumes:
      - mongo-data:/data/db  # Docker-managed volume for MongoDB
    networks:
      - mern-network

networks:
  mern-network:

volumes:
  backend-data:
  frontend-data:
  mongo-data:
